localization:
  default: en
  fallback: en
  locales:
    - ca
    - en
    - fr

social:
  twitter: https://www.twitter.com/andorrapavilion
  instagram: https://www.instagram.com/andorrapavilion2020

sections:
  expo:
    name: expo
    gallery:
      slides:
        - /images/expo_aerial_render

  pavilion:
    name: pavilion
    gallery:
      interval: 5
      pagination: true
      slides:
        - /images/outdoors
        - /images/model3d
        - /images/videowall
    agenda:
      date:
        dateStyle: medium
        timeStyle: short

  discover:
    name: discover
    gallery:
      interval: 5
      pagination: false
      slides:
        - /images/wellness
        - /images/winter
        - /images/heritage
        - /images/summer
        - /images/shopping

# Airtable API config
api:
  base: appohIYQXUkv2twZm
  resources:
    AGENDA:
      endpoint: agenda
      options:
        fields:
          - from
          - until
          - cover
        sort:
          from: asc
        where:
          constraints: 1
          active:
            checked: true
